# Generated by Django 4.1 on 2024-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shareprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volumn', models.PositiveBigIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=3)),
                ('changePercent', models.DecimalField(decimal_places=5, max_digits=6)),
                ('symbol', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
